### ISSUE TITLE
[server] mod won't load; requesting screen access

### ISSUE THREAD

**Issue by afewlines** [Necr0/CoyoteLib#1]
tried to start a forge server (1.16) with this mod (+double jump) and the library gave this error:

`Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER`

works great in single player though!

**Comment by QbDesu** [comment]
Argh dammit! I introduced this bug when I fixed ~~a crash which happened in Open to LAN~~ GameRule registration to be executed in time for the world creation GUI >.< I'm fixing this now, fixed version should be up soon

**Comment by QbDesu** [comment]
Thank you for reporting the bug, a fixed version(1.3.3) is now on curseforge. If you run into any other issues be sure to let me know. https://www.curseforge.com/minecraft/mc-mods/coyotelib/files/3015737
